### ISSUE TITLE
Fix user survey questionnaire

### ISSUE THREAD

**Issue by asiripanich** [asiripanich/e-mission-phone#11]
Fix and update user profile survey before the pilot survey gets launched.

- [x] age group 25 - 33 is missing
- [x] replace those annoying location questions with address fields

![Screen Shot 2019-07-15 at 8 12 46 pm](https://user-images.githubusercontent.com/17020181/61209421-0b8acc00-a73d-11e9-9c08-397aff82caca.png)

**Comment by atton16** [comment]
PR https://github.com/e-mission/e-mission-phone/pull/607
