### ISSUE TITLE
Update mode inference method to GIS mapping

### ISSUE THREAD

**Issue by asiripanich** [asiripanich/e-mission-phone#12]
During our last Skype meeting with Shankari she mentioned something about GIS mapping for mode inference. Basically, this feature try to infer the mode by using the taken route of the user and send a query to OpenStreetMap to check if the user could have taken public transport etc. 

@atton16 could you look more into this and see how hard it is to add this feature to our branch. If I remember correctly FabMob also using this feature for mode inference.

**Comment by asiripanich** [comment]
A starting point.. https://github.com/e-mission/e-mission-server/pull/578

**Comment by atton16** [comment]
So we will switch branch to `gis-based-mode-detection`?

**Comment by asiripanich** [comment]
any potential issues I should be aware of if we were to switch?

**Comment by atton16** [comment]
not sure.

**Comment by atton16** [comment]
switched!
