### ISSUE TITLE
Disable trip-end notification by default

### ISSUE THREAD

**Issue by asiripanich** [asiripanich/e-mission-phone#16]
Stop those annoying notifications

**Comment by atton16** [comment]
These ??

![IMG_2830](https://user-images.githubusercontent.com/5247367/63677979-67ef0a00-c818-11e9-9c9a-bf65e11cbdb3.jpg)

**Comment by asiripanich** [comment]
Yes

**Comment by atton16** [comment]
PR https://github.com/e-mission/e-mission-phone/pull/604
