### ISSUE TITLE
Use Google address autocomplete in User profile

### ISSUE THREAD

**Issue by asiripanich** [asiripanich/e-mission-phone#18]
Is it possible to use Google address autocomplete in Enketo? 
Replace those location questions where coordinates must be answered with an address field that uses Google address autocomplete service.

related #11

**Comment by atton16** [comment]
Unfortunately, we cannot interfere with how Enketo render the survey on the screen.

I cannot interfere with any of the code during the render time.

However, we can file an issue to Enketo to as feature request.

**Comment by asiripanich** [comment]
@atton16 In that case we will not ask about the user's place of work, place of residence and place of education. Instead we can infer from their travel dairy. To have this feature working may add more work to your plate at this point. An ideal solution would be creating our own survey (without using enketo framework) but that would take too much time at this point since we want to deploy it as soon as possible.
