### ISSUE TITLE
Use profile should only need to be filled once for each account.

### ISSUE THREAD

**Issue by asiripanich** [asiripanich/e-mission-phone#30]
@atton16 I think there has been some changes that undo the logic. Can you please look into it?

**Comment by atton16** [comment]
What happen?

**Comment by asiripanich** [comment]
not sure why it has asked me to fill in the survey again.

**Comment by asiripanich** [comment]
So apparently, when this happened I was testing the branches so I had to install and reinstall multiple times within minutes apart. So it was the issue of the app wasn't syncing my user profile answers to the server, hence the answers had not been stored when I logged in the second and third times.. .
