### ISSUE TITLE
update trip_comfirm_options.json

### ISSUE THREAD

**Issue by asiripanich** [asiripanich/e-mission-phone#31]
@atton16 I recently updated mode and purpose categories. I guess this file has to be updated as well right?  to make them appear correctly on the diary tab?

https://github.com/atton16/e-mission-phone/blob/bfadf40ba2acc3cb98d44e894aa0235890c03742/www/json/trip_confirm_options.json.sample#L1-L25

**Comment by atton16** [comment]
No, the survey is independent to the original trip confirm dialog system.

**Comment by asiripanich** [comment]
so we can safely delete that json file right?

**Comment by atton16** [comment]
I would suggest leaving it as is.

**Comment by asiripanich** [comment]
Ahh ok. I have to revert that commit that deleted the file in the draft PR.
