### ISSUE TITLE
An input issue on the user profile form

### ISSUE THREAD

**Issue by asiripanich** [asiripanich/e-mission-phone#34]
Once I enter a text input on the form, the screen will be shifted to other location or if it snaps correctly it will be hard to exit that input box. Unless there is another text input box visible within the screen, then I can tap on the other text input box to exit the first box.

![RPReplay_Final1587879526](https://user-images.githubusercontent.com/17020181/80299103-19de3c00-87d5-11ea-8223-f9f590b8d58f.gif)

**Comment by asiripanich** [comment]
Reported by the same user #33

**Comment by asiripanich** [comment]
@shankari do you have any advice for us? I tried on safari and firefox browsers on my iPhone and they seem fine. But when we use it on emTripLog that weird behavior appear. You can try the survey here: up.amarin.dev

**Comment by asiripanich** [comment]
We about to deploy our study next week and this is the most urgent matter to us. This will definitely impact all the users in joining our survey. 

The most doable and also the easiest option would be to launch the survey profile survey by opening web-browser on emtriplog, like what we have done for the post experience survey.  

What I understand is the UI problem cannot be easily fixed since it has to do with how phonegap renders enketo? correct me if I'm wrong.

**Comment by shankari** [comment]
@asiripanich I don't have any immediate advice for you. I haven't tested your app any more than you have 😄

If it works in Safari and Firefox then it is almost certainly something to do with the browser used by emTripLog.

Does this happen on both android and iOS? It is not clear which phone your original video is being generated on...

**Comment by shankari** [comment]
Does this also happen in the emulator? Is there any error in the logs corresponding to it? I don't have a lot of time to spend on this today because I am presenting (virtually) at the ICLR climate change workshop.

**Comment by asiripanich** [comment]
> @asiripanich I don't have any immediate advice for you. I haven't tested your app any more than you have 😄
> 
> 
> 
> If it works in Safari and Firefox then it is almost certainly something to do with the browser used by emTripLog.
> 
> 
> 
> Does this happen on both android and iOS? It is not clear which phone your original video is being generated on...

It was on my iphone. I dont no about android. I will report once I try it.

**Comment by asiripanich** [comment]
> Does this also happen in the emulator? Is there any error in the logs corresponding to it? I don't have a lot of time to spend on this today because I am presenting (virtually) at the ICLR climate change workshop.

@atton16 did u recall seeing this on the emulator as well? No need to try if u dont remember.
