### ISSUE TITLE
User Profile Survey via InAppBrowser

### ISSUE THREAD

**Issue by atton16** [asiripanich/e-mission-phone#35]
We are moving from embedded survey to online survey by opening the survey link with in-app browser.

Now we need to work on communication between the in-app browser and the current `$scope`.

What we are trying to achieve is when user submit the survey, we wanted to redirect them to the main view.

So what we need is the IAB **postMessage API** from `cordova-plugin-inappbrowser` version `3.1.0-dev`. (ref: https://www.andreszsogon.com/how-to-close-inappbrowser-window-in-cordova-by-itself/)

postMessage API allows JavaScript code from inside iab to communicate to the current `$scope`. But we are using the customized `inappbrowser` version `1.6`. I am not sure why we are using the custom version but I am certain there is a good reason behind it.

So I am thinking either upgrade IAB plugin to `3.1.0-dev` or perhaps there is a workaround that you could point us to.

**Comment by asiripanich** [comment]
tranfering this issue to the main repo.

**Comment by asiripanich** [comment]
Whoops! I don't think I can do that.

**Comment by atton16** [comment]
- - wrong repo

**Comment by asiripanich** [comment]
I copied this issue to the main repo see the mention above
